---

# install packages
- name: Install list of packages
  apt: pkg={{item}} state=installed
  with_items:
    - build-essential
    - g++
    - flex
    - bison
    - gperf
    - ruby
    - perl
    - libsqlite3-dev
    - libfontconfig1-dev
    - libicu-dev
    - libfreetype6
    - libssl-dev
    - libpng-dev
    - libjpeg-dev
    - python
    - libx11-dev
    - libxext-dev

- copy: src=phantomjs_1.9.8 dest=/usr/local/share/phantomjs_1.9.8 owner=root group=root mode=0711 force=no
- copy: src=phantomjs_2.0.0 dest=/usr/local/share/phantomjs_2.0.0 owner=root group=root mode=0711 force=no
- file: src=/usr/local/share/phantomjs_2.0.0 dest=/usr/local/bin/phantomjs state=hard
